--SELECT * 
--FROM CUSTOMERS
-------------------------------------------------
--SELECT* 
--FROM CUSTOMERS
--WHERE  CUSTOMERID LIKE 'C%'	-- BURADA '%' karakteri kullanýldý. C HARFÝ ÝLE BAÞLAYANLARI GETÝRDÝ
-------------------------------------------------
--SELECT* 
--FROM CUSTOMERS
--WHERE  CUSTOMERID LIKE '%D'
-------------------------------------------------
--SELECT* 
--FROM CUSTOMERS
--WHERE  ContactName LIKE '%MAS%'
-------------------------------------------------
--SELECT* 
--FROM CUSTOMERS
--WHERE  CompanyName LIKE '_R%'
-------------------------------------------------
--SELECT* 
--FROM CUSTOMERS
--WHERE  CompanyName LIKE 'A__%'
-------------------------------------------------
--SELECT* 
--FROM CUSTOMERS
--WHERE  ContactName LIKE 'A%O'
-------------------------------------------------

